on: push
name: Build and Publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/npm@master
      with:
        args: install
    - name: Test
      uses: ianwalter/puppeteer@master
      with:
        entrypoint: npm
        args: test
    - name: Publish
      uses: mikeal/merge-release@master
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - uses: mikeal/bundle-size-action@master
      if: github.ref == 'refs/heads/master'
    - uses: mikeal/publish-to-github-action@master
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
